### ISSUE TITLE
Garage in Pillbox.

### ISSUE THREAD

**Issue by Midori33** [HollywoodHeists/public#74] opened 2023-01-06 06:27 UTC
Could we get an employee garage under pillbox to store our personal cars while on shift?

**Comment by ItsGabble** [comment] 2023-01-07 21:51
Closing as a duplicate of the private EMS repo. Pass these requests up the EMS chain of command so they don't get lost in public repo, please :)

**Closed as completed by ItsGabble** 2023-01-07 21:51 UTC
