### ISSUE TITLE
Fishing - Metal Boxes

### ISSUE THREAD

**Issue by RockemRobotics** [HollywoodHeists/public#82] opened 2023-01-07 17:14 UTC
The metal boxes I pull up while fishing seem to give zero loot when opening them. I can't tell if this is the intended behavior of the metal boxes, because when I open one there's a timed pop-up that tells me I'm opening the box and then... nothing. I get nothing in my inventory, I get no pop-up telling me I found nothing, I get no messages at all.

If they're supposed to be usually empty and only sometimes give something, a message telling me "oh you didn't find anything" would be great, otherwise I have to assume this is a bug.

**Comment by MrKyRy** [comment] 2023-01-10 00:39
I can confirm that after fishing for some time all of the metal boxes when you open them give you zero items and the prompt says "opening box" then after opening it does not say anything. I assume it is supposed to have a message after saying either "loot found" or " no items found" and with those items you can do other things. Unless the intended purpose of the metal boxes is to only have a small chance of having items in them. But I have opened 6 metal boxes and nothing. Unsure if it is a bug or this is the intended purpose.

**Comment by iTzaDeAdHoBo** [comment] 2023-01-14 10:25
metal tins still show nothing when being opened, also are fishing tins supposed to do anything or are they just trash because it would be interesting if they can be used at recycling for metal scrap or something.

**Comment by AliAliJr** [comment] 2023-04-13 03:56
was fixed, forgot to close this issue.

**Closed as completed by AliAliJr** 2023-04-13 03:56 UTC
